"""
Wrapper over the FLAI library (González-Sendino et al., 2024) to:

  1. Learn the causal graph from the original data.
  2. Mitigate relationships and conditional probabilities (Fair Causal Model).
  3. Generate Fair Data via forward sampling.
  4. Generate data with simple resampling (baseline Liu et al., 2024).

FLAI reference: https://github.com/rugonzs/FLAI
"""

import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.utils import resample

try:
    from FLAI import data as flai_data
    from FLAI import causal_graph
    import bnlearn as bn
    print("[fair_data] Backend: FLAI")
except ImportError:
    flai_data = causal_graph = bn = None
    print("[fair_data] WARNING: flai-causal or bnlearn not installed. Run: pip install flai-causal bnlearn")

# Maximum unique values per column allowed for FLAI.
# Columns with more values are automatically discretized into MAX_CARD bins.
MAX_CARD = 10


def _discretize_for_flai(df: pd.DataFrame, n_bins: int = 5) -> tuple:
    """Discretize high-cardinality columns using pd.cut into n_bins bins.
    Columns with ≤ MAX_CARD unique values are left intact.

    String/categorical columns are label-encoded so FLAI can process them.
    The encoding mapping is returned so callers can restore semantic labels
    in the generated data.

    For continuous numeric columns that are binned, the bin midpoints are
    recorded in ``num_bin_midpoints`` so the generated data can be
    inverse-transformed back to interpretable numeric values before saving.

    Args:
        df: Input DataFrame.
        n_bins: Number of bins for continuous high-cardinality columns.

    Returns:
        tuple[pd.DataFrame, dict, dict]: Discretized int64 DataFrame, a
            ``cat_maps`` dict mapping column name -> {int_code: original_str}
            for every column that was label-encoded from strings, and a
            ``num_bin_midpoints`` dict mapping column name -> {bin_int: midpoint}
            for every continuous column that was discretized with pd.cut.
    """
    df = df.copy()
    cat_maps = {}
    num_bin_midpoints = {}
    for col in df.columns:
        if df[col].dtype == object or str(df[col].dtype) == "category":
            # String column: encode to int, record inverse mapping
            categories = sorted(df[col].astype(str).unique())
            code_map = {cat: i for i, cat in enumerate(categories)}
            inv_map  = {i: cat for cat, i in code_map.items()}
            cat_maps[col] = inv_map
            df[col] = df[col].astype(str).map(code_map).astype(int)
        elif df[col].nunique() > MAX_CARD:
            # Continuous column: bin and record midpoints for inverse transform
            binned, bin_edges = pd.cut(df[col], bins=n_bins, labels=False, retbins=True)
            midpoints = {
                i: round((bin_edges[i] + bin_edges[i + 1]) / 2)
                for i in range(n_bins)
            }
            num_bin_midpoints[col] = midpoints
            df[col] = binned.astype(int)
        else:
            df[col] = df[col].astype(int)
    return df, cat_maps, num_bin_midpoints


def _restore_categories(df: pd.DataFrame, cat_maps: dict, num_bin_midpoints: dict = None) -> pd.DataFrame:
    """Restore original string labels and numeric scales in columns that were encoded.

    Args:
        df: DataFrame with integer-coded columns (as generated by FLAI).
        cat_maps: Dict {col: {int_code: original_str}} returned by
            ``_discretize_for_flai``.
        num_bin_midpoints: Dict {col: {bin_int: midpoint}} returned by
            ``_discretize_for_flai``. If provided, continuous binned columns
            are inverse-transformed to their midpoint values so that LLMs
            receive interpretable numeric values instead of bin indices.

    Returns:
        DataFrame with string labels and numeric scales restored.
    """
    df = df.copy()
    for col, inv_map in cat_maps.items():
        if col in df.columns:
            # FLAI-generated codes may be floats; cast to int first
            df[col] = df[col].apply(
                lambda v: inv_map.get(int(round(v)), str(int(round(v)))) if pd.notna(v) else v
            )
    if num_bin_midpoints:
        for col, midpoints in num_bin_midpoints.items():
            if col in df.columns:
                n_bins = len(midpoints)
                df[col] = df[col].apply(
                    lambda v: midpoints.get(int(round(v)) % n_bins, midpoints[0]) if pd.notna(v) else v
                )
    return df


# ---------------------------------------------------------------------------
# CAUSAL FAIR DATA GENERATION (FLAI)
# ---------------------------------------------------------------------------

def generate_fair_data_causal(df: pd.DataFrame, target_col: str, sensitive_features: list, n_samples: int = None, method: str = "bayes", save_path: Path = None) -> pd.DataFrame:
    """Generate Fair Data using the FLAI mitigated causal model.

    Args:
        df: Original DataFrame with all features.
        target_col: Name of the label column.
        sensitive_features: List of protected attributes (e.g. ['sex', 'race']).
        n_samples: Number of samples to generate. If None, uses the same size as df.
        method: Sampling method ('bayes' — only applies with FLAI backend).
        save_path: Optional path to save the resulting CSV.

    Returns:
        DataFrame with generated Fair Data.
    """
    if flai_data is None:
        raise ImportError("flai-causal or bnlearn not installed. Run: pip install flai-causal bnlearn")

    if n_samples is None:
        n_samples = len(df)

    # Discretize high-cardinality columns — FLAI builds CPD tables with a
    # cartesian product over parent values. Continuous columns with dozens of
    # unique values cause the product to reach millions of combinations.
    # cat_maps captures string→int encodings and num_bin_midpoints captures
    # bin intervals so we can restore interpretable values afterwards.
    df_disc, cat_maps, num_bin_midpoints = _discretize_for_flai(df, n_bins=5)
    print(f"[FLAI] Cardinalities after discretization: "
          f"{ {c: df_disc[c].nunique() for c in df_disc.columns} }")

    # Learn causal structure with controlled max_indegree
    print("[FLAI] Learning causal structure")
    graph_struct = bn.structure_learning.fit(
        df_disc, methodtype='hc', scoretype='bic', max_indegree=3, verbose=0
    )
    edges = graph_struct['model_edges']

    # Connect isolated nodes to target
    nodes_in_graph = {n for e in edges for n in e}
    isolated = [c for c in df_disc.columns if c not in nodes_in_graph and c != target_col]
    for node in isolated:
        edges = edges + [(node, target_col)]
    if isolated:
        print(f"[FLAI] Isolated nodes connected to target: {isolated}")
    print(f"[FLAI] Final edges: {edges}")

    # Causal mitigation via FLAI
    flai_dataset = flai_data.Data(df_disc, transform=False)
    graph = causal_graph.CausalGraph(
        flai_dataset, node_edge=edges, target=target_col, indepence_test=False
    )
    print("[FLAI] Mitigating causal relationships...")
    graph.mitigate_edge_relation(sensible_feature=sensitive_features)

    # Workaround FLAI bug: reattach orphan nodes after mitigate_edge_relation
    # mitigate_edge_relation() can leave nodes with no edges (orphans):
    #   - sensitive attributes lose their outgoing edges (by design)
    #   - normal nodes can become isolated if their only edge connected to a sensitive node
    # FLAI does not handle these orphans when rebuilding the DAG in mitigate_calculation_cpd(),
    # which produces: "CPD defined on variable not in the model".
    print("[FLAI] Mitigating CPDs (with FLAI bug workaround)...")
    edges_after = list(graph.graph['model_edges'])
    nodes_after = {n for e in edges_after for n in e}
    all_nodes = list(df_disc.columns)
    orphans = [n for n in all_nodes if n not in nodes_after and n != target_col]
    if orphans:
        for n in orphans:
            edges_after = edges_after + [(n, target_col)]
        graph.graph['model_edges'] = edges_after
        graph.graph['model'] = bn.make_DAG(edges_after, verbose=0)['model']
        print(f"[FLAI] Orphan nodes reconnected to target: {orphans}")
    graph.mitigate_calculation_cpd(sensible_feature=sensitive_features)

    # Renormalize all CPDs after mitigation — FLAI can leave CPDs that don't sum to 1,
    # which causes pgmpy's check_model() to raise ValueError during sampling.
    for cpd in graph.graph['model'].cpds:
        raw = np.array(cpd.values)
        n_states = raw.shape[0]
        flat = raw.reshape(n_states, -1)
        s = flat.sum(axis=0, keepdims=True)
        s[s == 0] = 1
        cpd.values = (flat / s).reshape(raw.shape)

    print(f"[FLAI] Generating {n_samples} samples (method={method})...")
    result = graph.generate_dataset(n_samples=n_samples, methodtype=method)
    fair_df = result.data if hasattr(result, "data") else result
    fair_df = fair_df[[c for c in df.columns if c in fair_df.columns]]

    # Restore original string labels and numeric scales so the generated
    # D2 CSV contains interpretable values (e.g. "Bachelors" not "11",
    # hours-per-week ~40 not bin index 3).
    if cat_maps or num_bin_midpoints:
        fair_df = _restore_categories(fair_df, cat_maps, num_bin_midpoints)
        if cat_maps:
            print(f"[FLAI] Restored string labels for columns: {list(cat_maps.keys())}")
        if num_bin_midpoints:
            print(f"[FLAI] Restored numeric midpoints for columns: {list(num_bin_midpoints.keys())}")

    if save_path:
        fair_df.to_csv(save_path, index=False)
        print(f"[fair_data] Fair Data saved to {save_path}")

    print(f"[fair_data] Fair Data generated: {fair_df.shape}")
    return fair_df


# ---------------------------------------------------------------------------
# SIMPLE RESAMPLING (baseline Liu et al., 2024)
# ---------------------------------------------------------------------------

def generate_resampled_data(df: pd.DataFrame, sensitive_feature: str, privileged_value: int, strategy: str = "oversample", save_path: Path = None) -> pd.DataFrame:
    """Generate balanced data via simple resampling.

    Replicates the baseline from Liu et al. (NAACL 2024): oversampling the
    minority group or undersampling the majority group.

    Args:
        df: Original DataFrame.
        sensitive_feature: Protected attribute to balance.
        privileged_value: Value of the privileged group (e.g. 1=Male).
        strategy: 'oversample' or 'undersample'.
        save_path: Optional path to save the resulting CSV.

    Returns:
        Balanced DataFrame.
    """
    priv = df[df[sensitive_feature] == privileged_value]
    unpriv = df[df[sensitive_feature] != privileged_value]

    n_priv = len(priv)
    n_unpriv = len(unpriv)

    print(f"[Resample] {sensitive_feature}: privileged={n_priv}, underprivileged={n_unpriv}")

    if strategy == "oversample":
        target_n = max(n_priv, n_unpriv)
        if n_priv > n_unpriv:
            unpriv_resampled = resample(unpriv, replace=True, n_samples=target_n, random_state=42)
            resampled_df = pd.concat([priv, unpriv_resampled])
        else:
            priv_resampled = resample(priv, replace=True, n_samples=target_n, random_state=42)
            resampled_df = pd.concat([priv_resampled, unpriv])
    elif strategy == "undersample":
        target_n = min(n_priv, n_unpriv)
        if n_priv > n_unpriv:
            priv_resampled = resample(priv, replace=False, n_samples=target_n, random_state=42)
            resampled_df = pd.concat([priv_resampled, unpriv])
        else:
            unpriv_resampled = resample(unpriv, replace=False, n_samples=target_n, random_state=42)
            resampled_df = pd.concat([priv, unpriv_resampled])
    else:
        raise ValueError(f"strategy must be 'oversample' or 'undersample', got: {strategy}")

    resampled_df = resampled_df.sample(frac=1, random_state=42).reset_index(drop=True)

    print(f"[Resample] Result: {resampled_df.shape} | "
          f"privileged={len(resampled_df[resampled_df[sensitive_feature]==privileged_value])}, "
          f"underprivileged={len(resampled_df[resampled_df[sensitive_feature]!=privileged_value])}")

    if save_path:
        resampled_df.to_csv(save_path, index=False)
        print(f"[Resample] Saved to {save_path}")

    return resampled_df


# ---------------------------------------------------------------------------
# MAKE ALL HAPPEN
# ---------------------------------------------------------------------------

def prepare_all_datasets(df: pd.DataFrame, dataset_name: str, target_col: str, sensitive_features: list, privileged_values: dict, output_dir: Path, n_samples: int = None) -> dict:
    """Generate the three dataset versions required for the experiment.

    Versions generated:
    - D1: original data (direct copy).
    - D2: causal Fair Data (FLAI).
    - D3: oversampling resampling on the first protected attribute (baseline).

    Saves everything to output_dir/{dataset_name}/

    Args:
        df: Preprocessed original DataFrame.
        dataset_name: Dataset name ('adult', 'compas', 'german').
        target_col: Name of the target column.
        sensitive_features: List of protected attributes.
        privileged_values: Dictionary {feature: privileged_value}.
        output_dir: Root output directory.
        n_samples: Samples to generate for D2. None = same count as df.

    Returns:
        Dictionary with keys 'D1', 'D2', 'D3' and their loaded DataFrames.
    """
    out = output_dir / dataset_name
    out.mkdir(parents=True, exist_ok=True)

    # D1 — Original
    d1_path = out / "D1_original.csv"
    df.to_csv(d1_path, index=False)
    print(f"\n[D1] Original saved: {d1_path}")

    # D2 — Causal Fair Data
    d2_path = out / "D2_fair_causal.csv"
    if d2_path.exists():
        print(f"\n[D2] Already exists, skipping generation: {d2_path}")
    else:
        print("\n[D2] Generating causal Fair Data")
        generate_fair_data_causal(
            df=df,
            target_col=target_col,
            sensitive_features=sensitive_features,
            n_samples=n_samples,
            save_path=d2_path,
        )

    # D3 — Resampling (uses the first protected attribute as primary)
    primary_sensitive = sensitive_features[0]
    d3_path = out / "D3_resampled.csv"
    if d3_path.exists():
        print(f"\n[D3] Already exists, skipping generation: {d3_path}")
    else:
        print("\n[D3] Generating resampled data")
        generate_resampled_data(
            df=df,
            sensitive_feature=primary_sensitive,
            privileged_value=privileged_values[primary_sensitive],
            strategy="oversample",
            save_path=d3_path,
        )

    print(f"\n[prepare_all_datasets] Completed for '{dataset_name}'.")
    return {
        "D1": pd.read_csv(d1_path),
        "D2": pd.read_csv(d2_path),
        "D3": pd.read_csv(d3_path),
    }
